# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 20:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'tracker', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('requester_name', models.CharField(max_length=3000)),
                ('email', models.EmailField(max_length=254)),
                ('accession', models.CharField(max_length=200)),
                ('study_name', models.CharField(max_length=3000)),
                ('source', models.CharField(max_length=3000)),
                ('link', models.URLField(max_length=3000)),
                ('samples', models.IntegerField()),
                ('tissue', models.CharField(max_length=3000)),
                ('adult_or_pediatric', models.CharField(choices=[(0, b'Unknown'), (1, b'Adult'), (2, b'Pediatric'), (3, b'Both')], default=0, max_length=7)),
                ('PMID', models.IntegerField()),
                ('citation', models.CharField(max_length=3000)),
                ('details', models.CharField(max_length=3000)),
                ('access', models.CharField(choices=[(0, b'Unknown'), (1, b'Open'), (2, b'Restricted')], default=0, max_length=10)),
                ('priority', models.IntegerField(default=0)),
                ('trackerID', models.CharField(choices=[(b'Requested', b'Requested'), (b'Staged', b'Staged'), (b'Database', b'Database'), (b'Application', b'Application')], default=b'Requested', max_length=11)),
            ],
        ),
    ]
