# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_squashed_0001_initial'),
    ]

    operations = [
    ]
