# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20160107_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='PMID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='access',
            field=models.CharField(choices=[(b'Unknown', b'Unknown'), (b'Open', b'Open'), (b'Restricted', b'Restricted')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='adult_or_pediatric',
            field=models.CharField(choices=[(b'Unknown', b'Unknown'), (b'Adult', b'Adult'), (b'Pediatric', b'Pediatric'), (b'Both', b'Both')], default=b'Unknown', max_length=50),
        ),
    ]
