# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20160113_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='sample_type',
            field=models.CharField(default='-', max_length=3000),
            preserve_default=False,
        ),
    ]
