# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_tracker_sample_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='access',
            field=models.CharField(choices=[(b'Unknown', b'Unknown'), (b'Open', b'Open'), (b'Restricted', b'Restricted')], default=b'unknown', max_length=10),
        ),
    ]
