# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20160113_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='cbio_link',
            field=models.URLField(default=0, max_length=3000),
            preserve_default=False,
        ),
    ]
