# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_tracker_cbio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='key',
            field=models.CharField(default=uuid.uuid1, max_length=64),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='trackerID',
            field=models.CharField(choices=[(b'Requested', b'Requested'), (b'Downloaded', b'Downloaded'), (b'Staged', b'Staged'), (b'Database', b'Database'), (b'CbioPortal', b'CbioPortal'), (b'Cavatica', b'Cavatica')], default=b'Requested', max_length=11),
        ),
    ]
