# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_tracker_cbio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='L1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='trackerID',
            field=models.CharField(choices=[(b'Requested', b'Requested'), (b'Downloaded', b'Downloaded'), (b'Staged', b'Staged'), (b'Database', b'Database'), (b'cBioPortal', b'cBioPortal'), (b'Cavatica', b'Cavatica')], default=b'Requested', max_length=11),
        ),
    ]
