# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20160204_1622'),
        ('tracker', '0008_auto_20160203_1815'),
    ]

    operations = [
    ]
