# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20160209_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='uuid',
            field=models.IntegerField(default=uuid.uuid1),
        ),
    ]
