# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('tracker', '0014_auto_20160211_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackergroup',
            name='access_link',
            field=models.SlugField(default=None),
        ),
        migrations.AddField(
            model_name='trackergroup',
            name='group',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group_id', to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackeruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
