# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20160215_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='PMID',
            field=models.IntegerField(blank=True, help_text=b'121326', null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='accession',
            field=models.CharField(blank=True, help_text=b'EGA-0000000', max_length=200),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='citation',
            field=models.CharField(blank=True, help_text=b'John, et. al. Nature 2016', max_length=3000),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='details',
            field=models.CharField(blank=True, help_text=b'WTS, WGS, WES, RNA-Seq', max_length=3000),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='group',
            field=models.CharField(choices=[(b'0', b'None'), (b'1', b'CBTTC'), (b'2', b'SU2C'), (b'3', b'PNOC'), (b'9', b'PUBLIC')], default=b'0', help_text=b'PNOC, CBTTC, SU2C, PUBLIC', max_length=3000),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='link',
            field=models.URLField(blank=True, help_text=b'https://www.cbttc.org', max_length=3000),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='name',
            field=models.CharField(default=b'source_cancer_sampletype_num', max_length=3000),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='priority',
            field=models.IntegerField(blank=True, default=0, help_text=b'0-none, 1-low, 2-medium, 3-high'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='requester_name',
            field=models.CharField(help_text=b'Jane Smith', max_length=3000),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='sample_type',
            field=models.CharField(blank=True, help_text=b'tissue, cell line, or xenograft', max_length=3000),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='source',
            field=models.CharField(blank=True, help_text=b'Childrens Hospital of Philadelpia', max_length=3000),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='study_name',
            field=models.CharField(help_text=b'TCGA Invasive Breast Carcinoma', max_length=3000),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tissue',
            field=models.CharField(blank=True, help_text=b'breast carcinoma', max_length=3000),
        ),
    ]
