# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_auto_20160216_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='name',
        ),
    ]
