# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_remove_tracker_name'),
    ]

    operations = [
    ]
