# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 17:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uuid', models.IntegerField(default=uuid.uuid1)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('requester_name', models.CharField(max_length=3000)),
                ('email', models.EmailField(max_length=254)),
                ('accession', models.CharField(blank=True, max_length=200)),
                ('study_name', models.CharField(max_length=3000)),
                ('source', models.CharField(blank=True, max_length=3000)),
                ('link', models.URLField(blank=True, max_length=3000)),
                ('cbio_link', models.URLField(max_length=3000)),
                ('samples', models.IntegerField(blank=True)),
                ('tissue', models.CharField(blank=True, max_length=3000)),
                ('adult_or_pediatric', models.CharField(choices=[(b'Unknown', b'Unknown'), (b'Adult', b'Adult'), (b'Pediatric', b'Pediatric'), (b'Both', b'Both')], default=b'Unknown', max_length=50)),
                ('PMID', models.IntegerField(blank=True, null=True)),
                ('citation', models.CharField(blank=True, max_length=3000)),
                ('sample_type', models.CharField(blank=True, max_length=3000)),
                ('details', models.CharField(blank=True, max_length=3000)),
                ('access', models.CharField(choices=[(b'Unknown', b'Unknown'), (b'Open', b'Open'), (b'Restricted', b'Restricted')], default=b'Unknown', max_length=10)),
                ('priority', models.IntegerField(blank=True, default=0)),
                ('trackerID', models.CharField(choices=[(b'0', b'Requested'), (b'1', b'Downloaded'), (b'2', b'Staged'), (b'3', b'Database'), (b'4', b'CbioPortal'), (b'5', b'Cavatica')], default=b'0', max_length=11)),
                ('L1', models.IntegerField(default=0)),
                ('group', models.CharField(choices=[(b'0', b'None'), (b'1', b'CBTTC'), (b'2', b'SU2C'), (b'3', b'PNOC'), (b'9', b'PUBLIC')], default=b'0', help_text=b'PNOC, CBTTC, SU2C, PUBLIC', max_length=3000)),
                ('confirmation', models.CharField(choices=[(b'0', b'None'), (b'1', b'Email me a confirmation of my request')], default=b'0', max_length=100)),
                ('subscription', models.CharField(choices=[(b'0', b'None'), (b'1', b'Email me when my request is available'), (b'2', b'Email me at every step along the request')], default=b'0', max_length=100)),
                ('summary', models.CharField(choices=[(b'0', b'None'), (b'1', b'Email me a weekly summary of Data Tracker requests'), (b'2', b'Email me a monthly summary of Data Tracker requests')], default=b'0', max_length=100)),
            ],
            options={
                'ordering': ('-id', 'time', 'priority'),
                'permissions': (('private', 'Can be seen and used by the owner only'), ('view_only', 'Can be only viewed by anyone'), ('user_limited', 'Can be seen by select users only'), ('group_limited', 'Can be accessed by a group or multiple groups'), ('public', 'Can be viewed and used by anyone')),
            },
        ),
        migrations.CreateModel(
            name='TrackerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('access_link', models.URLField(blank=True, max_length=3000)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_id', to='auth.Group')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('group', models.ManyToManyField(to='auth.Group')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
