# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20160222_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='sample_type',
            new_name='cancer_type',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='study_name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='link',
            new_name='s3_link',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='tissue',
            new_name='specimen_type',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trackeruser',
            name='username',
        ),
        migrations.AddField(
            model_name='tracker',
            name='dataset_name',
            field=models.CharField(default=b'source_cancertype_sampletype_ID', max_length=200),
        ),
        migrations.AddField(
            model_name='tracker',
            name='study_link',
            field=models.URLField(blank=True, max_length=245),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='group',
            field=models.CharField(choices=[(b'0', b'NONE'), (b'1', b'CBTTC'), (b'2', b'SU2C'), (b'3', b'PNOC'), (b'9', b'PUBLIC')], default=b'0', help_text=b'PNOC, CBTTC, SU2C, PUBLIC', max_length=245),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='samples',
            field=models.IntegerField(default=0),
        ),
    ]
