# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20160308_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=b'downloads'),
        ),
    ]
