# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20160317_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='L1',
        ),
        migrations.AddField(
            model_name='tracker',
            name='endpt',
            field=models.CharField(choices=[(b'0', b'Data goes to both Cavatica and cBioPortal'), (b'1', b'Data goes to cBioPortal only'), (b'2', b'Data goes to Cavatica only')], default=b'0', max_length=254),
        ),
        migrations.AddField(
            model_name='tracker',
            name='level',
            field=models.CharField(choices=[(b'0', b'L1 Data: FASTQ'), (b'1', b'L2 Data: VCF, BAM'), (b'2', b'L3 Data: Processed data')], default=b'0', max_length=230),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='group',
            field=models.CharField(choices=[(b'0', b'PRIVATE: requester access only'), (b'1', b'CBTTC'), (b'2', b'SU2C'), (b'3', b'PNOC'), (b'9', b'PUBLIC')], default=b'0', help_text=b'PNOC, CBTTC, SU2C, PUBLIC', max_length=245),
        ),
    ]
