# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 20:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3Direct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', s3direct.fields.S3DirectField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_read', 'Can read owned projects'), ('can_write', 'Can write to owned projects'), ('can_copy', 'Can copy owned projects'), ('can_execute', 'Can execute on owned projects'), ('is_admin', 'Is admin with super user priviledges')),
            },
        ),
        migrations.RenameField(
            model_name='trackeruser',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='trackeruser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='trackeruser',
            name='user',
        ),
        migrations.AddField(
            model_name='trackeruser',
            name='can_copy',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='trackeruser',
            name='can_execute',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='trackeruser',
            name='can_read',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='trackeruser',
            name='can_write',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='trackeruser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='trackeruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='trackeruser',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='trackeruser',
            name='is_admin',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='trackeruser',
            name='is_staff',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='trackeruser',
            name='is_superuser',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='trackeruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=b'downloads/%Y_%m_%d'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='group',
            field=models.CharField(choices=[(b'0', b'PRIVATE'), (b'1', b'CBTTC'), (b'2', b'SU2C'), (b'3', b'PNOC'), (b'9', b'PUBLIC')], default=b'9', help_text=b'PNOC, CBTTC, SU2C, PUBLIC', max_length=245),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='specimen_type',
            field=models.CharField(blank=True, help_text=b'tissue, cell line, or xenograft', max_length=245),
        ),
        migrations.AlterField(
            model_name='trackeruser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='trackeruser',
            table='auth_user',
        ),
    ]
