# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='name',
            field=models.CharField(default=b'source_cancer_type_number', max_length=200),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='cbio_link',
            field=models.URLField(max_length=245),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='citation',
            field=models.CharField(blank=True, max_length=245),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='details',
            field=models.CharField(blank=True, max_length=245),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='group',
            field=models.CharField(choices=[(b'0', b'None'), (b'1', b'CBTTC'), (b'2', b'SU2C'), (b'3', b'PNOC'), (b'9', b'PUBLIC')], default=b'0', help_text=b'PNOC, CBTTC, SU2C, PUBLIC', max_length=245),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='link',
            field=models.URLField(blank=True, max_length=245),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='requester_name',
            field=models.CharField(max_length=245),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='sample_type',
            field=models.CharField(blank=True, max_length=245),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='source',
            field=models.CharField(blank=True, max_length=245),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='study_name',
            field=models.CharField(max_length=345),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tissue',
            field=models.CharField(blank=True, max_length=245),
        ),
    ]
