# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20160308_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filetype',
            field=models.CharField(default='null', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=b'downloads/%Y_%m_%d'),
        ),
    ]
