# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20160308_2000'),
        ('tracker', '0008_auto_20160317_1604'),
    ]

    operations = [
    ]
