# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20160209_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='access',
            field=models.CharField(choices=[(b'Unknown', b'Unknown'), (b'Open', b'Open'), (b'Restricted', b'Restricted')], default=b'Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='group',
            field=models.CharField(choices=[(b'0', b'Private'), (b'1', b'CBTTC'), (b'2', b'SU2C'), (b'9', b'PUBLIC')], default=b'Private', max_length=3000),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='subscription',
            field=models.CharField(choices=[(b'0', b'Unsubscribe'), (b'1', b'Available'), (b'2', b'Step')], default=b'Unsubscribe', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='summary',
            field=models.CharField(choices=[(b'0', b'None'), (b'1', b'Weekly'), (b'2', b'Monthly')], default=b'None', max_length=7),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='trackerID',
            field=models.CharField(choices=[(b'0', b'Requested'), (b'1', b'Downloaded'), (b'2', b'Staged'), (b'3', b'Database'), (b'4', b'CbioPortal'), (b'5', b'Cavatica')], default=b'Requested', max_length=11),
        ),
    ]
